# Generated by Django 5.2.5 on 2025-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('books', 'Books'), ('sports', 'Sports'), ('stationary', 'Stationary'), ('electronic', 'electronic-items')], max_length=20)),
                ('items', models.CharField(choices=[('fiction-novels', 'Fictional-Novel'), ('non-fiction', 'Non-Fictional'), ('textbooks', 'Textbooks'), ('comic', 'Comic Books/Graphic Novels'), ('cook', 'Cookbooks'), ('balls', 'Balls'), ('bats', 'Bats-Racquets'), ('apparel', 'Apparels'), ('protective', 'Protective-Gears'), ('equipment', 'Equipments'), ('writing', 'Writing'), ('paper', 'Paper'), ('desk', 'Desk'), ('art', 'Art'), ('personal', 'Personal'), ('audio/video', 'Audio/Video'), ('computer', 'Computer'), ('accessories', 'Accessories')], max_length=30)),
                ('item_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='req_items/')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
